[package]
name = "iced_m3"
version = "0.1.0"
edition = "2024"
authors = [ "tpaau <tpaau-17db@tutamail.com>" ]
license = "MIT"

[dependencies]
iced = { version = "0.14.0", features = [ "advanced" ] }
iced_widget = "0.14.2"
num-traits = "0.2.19"
pollster = "1.0.1"
unicode-segmentation = "1.13.3"

[features]
advanced = []

[workspace]
members = [
  "demos/fonts",
  "demos/buttons",
  "demos/fab_menu",
  "demos/progress_indicators"
]

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
all-features = true
